#pragma once

/**
* Keycodes.
*
* Macros are defined in platform specific files.
*/

enum class KeyCode {
	Unknown = GE_KEY_UNKNOWN,

	// Printable keys
	Space = GE_KEY_SPACE,
	Apostrophe = GE_KEY_APOSTROPHE,
	Comma = GE_KEY_COMMA,
	Minus = GE_KEY_MINUS,
	Period = GE_KEY_PERIOD,
	Slash = GE_KEY_SLASH,
	_0 = GE_KEY_0,
	_1 = GE_KEY_1,
	_2 = GE_KEY_2,
	_3 = GE_KEY_3,
	_4 = GE_KEY_4,
	_5 = GE_KEY_5,
	_6 = GE_KEY_6,
	_7 = GE_KEY_7,
	_8 = GE_KEY_8,
	_9 = GE_KEY_9,
	Semicolon = GE_KEY_SEMICOLON,
	Equal = GE_KEY_EQUAL,
	A = GE_KEY_A,
	B = GE_KEY_B,
	C = GE_KEY_C,
	D = GE_KEY_D,
	E = GE_KEY_E,
	F = GE_KEY_F,
	G = GE_KEY_G,
	H = GE_KEY_H,
	I = GE_KEY_I,
	J = GE_KEY_J,
	K = GE_KEY_K,
	L = GE_KEY_L,
	M = GE_KEY_M,
	N = GE_KEY_N,
	O = GE_KEY_O,
	P = GE_KEY_P,
	Q = GE_KEY_Q,
	R = GE_KEY_R,
	S = GE_KEY_S,
	T = GE_KEY_T,
	U = GE_KEY_U,
	V = GE_KEY_V,
	W = GE_KEY_W,
	X = GE_KEY_X,
	Y = GE_KEY_Y,
	Z = GE_KEY_Z,
	LeftBracket = GE_KEY_LEFT_BRACKET,
	RightBracket = GE_KEY_RIGHT_BRACKET,
	Backslash = GE_KEY_BACKSLASH,
	GraveAccent = GE_KEY_GRAVE_ACCENT,
	World1 = GE_KEY_WORLD_1,
	World2 = GE_KEY_WORLD_2,

	// Function keys
	Escape = GE_KEY_ESCAPE,
	Enter = GE_KEY_ENTER,
	Tab = GE_KEY_TAB,
	Backspace = GE_KEY_BACKSPACE,
	Insert = GE_KEY_INSERT,
	Delete = GE_KEY_DELETE,
	RightArrow = GE_KEY_RIGHT_ARROW,
	LeftArrow = GE_KEY_LEFT_ARROW,
	DownArrow = GE_KEY_DOWN_ARROW,
	UpArrow = GE_KEY_UP_ARROW,
	PageUp = GE_KEY_PAGE_UP,
	PageDown = GE_KEY_PAGE_DOWN,
	Home = GE_KEY_HOME,
	End = GE_KEY_END,
	CapsLock = GE_KEY_CAPS_LOCK,
	ScollLock = GE_KEY_SCROLL_LOCK,
	NumLock = GE_KEY_NUM_LOCK,
	PrintScreen = GE_KEY_PRINT_SCREEN,
	Pause = GE_KEY_PAUSE,
	F1 = GE_KEY_F1,
	F2 = GE_KEY_F2,
	F3 = GE_KEY_F3,
	F4 = GE_KEY_F4,
	F5 = GE_KEY_F5,
	F6 = GE_KEY_F6,
	F7 = GE_KEY_F7,
	F8 = GE_KEY_F8,
	F9 = GE_KEY_F9,
	F10 = GE_KEY_F10,
	F11 = GE_KEY_F11,
	F12 = GE_KEY_F12,
	F13 = GE_KEY_F13,
	F14 = GE_KEY_F14,
	F15 = GE_KEY_F15,
	F16 = GE_KEY_F16,
	F17 = GE_KEY_F17,
	F18 = GE_KEY_F18,
	F19 = GE_KEY_F19,
	F20 = GE_KEY_F20,
	F21 = GE_KEY_F21,
	F22 = GE_KEY_F22,
	F23 = GE_KEY_F23,
	F24 = GE_KEY_F24,
	F25 = GE_KEY_F25,
	KeyPad0 = GE_KEY_KEY_PAD_0,
	KeyPad1 = GE_KEY_KEY_PAD_1,
	KeyPad2 = GE_KEY_KEY_PAD_2,
	KeyPad3 = GE_KEY_KEY_PAD_3,
	KeyPad4 = GE_KEY_KEY_PAD_4,
	KeyPad5 = GE_KEY_KEY_PAD_5,
	KeyPad6 = GE_KEY_KEY_PAD_6,
	KeyPad7 = GE_KEY_KEY_PAD_7,
	KeyPad8 = GE_KEY_KEY_PAD_8,
	KeyPad9 = GE_KEY_KEY_PAD_9,
	KeyPadDecimal = GE_KEY_KEY_PAD_DECIMAL,
	KeyPadDivide = GE_KEY_KEY_PAD_DIVIDE,
	KeyPadMultiply = GE_KEY_KEY_PAD_MULTIPLY,
	KeyPadSubtract = GE_KEY_KEY_PAD_SUBTRACT,
	KeyPadAdd = GE_KEY_KEY_PAD_ADD,
	KeyPadEnter = GE_KEY_KEY_PAD_ENTER,
	KeyPadEqual = GE_KEY_KEY_PAD_EQUAL,
	LeftShift = GE_KEY_LEFT_SHIFT,
	LeftCtrl = GE_KEY_LEFT_CTRL,
	LeftAlt = GE_KEY_LEFT_ALT,
	LeftSuper = GE_KEY_LEFT_SUPER,
	RightShift = GE_KEY_RIGHT_SHIFT,
	RightCtrl = GE_KEY_RIGHT_CTRL,
	RightAlt = GE_KEY_RIGHT_ALT,
	RightSuper = GE_KEY_RIGHT_SUPER,
	Menu = GE_KEY_MENU,

	MaxNumKeyCodes = GE_KEY_MAX_KEY_CODES
};
